### ISSUE TITLE
Remove usage of "core" from Twig files

### ISSUE THREAD

**Issue by micpap25** [Submitty/Submitty#10502] opened 2024-06-03 13:50 UTC
**What problem are you trying to solve with Submitty**
Currently, a large number of Twig files use `core` which is bad practice. 

**Describe the way you'd like to solve this problem**
Instead, relevant information should be accessed in the corresponding PHP file and put into the Twig file's template.

**Comment by williamjallen** [comment] 2024-06-07 16:00
This appears to be a duplicate of https://github.com/Submitty/Submitty/issues/4537.

**Closed by williamjallen** 2024-06-07 16:00 UTC
Labels: enhancement / feature request, Testing / Continuous Integration (CI), good first issue, refactor / coding style
