### ISSUE TITLE
Incorrect TA grading progress bar

### ISSUE THREAD

**Issue by Kevin-MM** [Submitty/Submitty#4198] opened 2019-07-25 16:17 UTC
**Describe the bug**
The progress bar on the TA grading interface can sometimes display a progress greater than true progress.  This is due to the fact that when total components to grade are counted up they do not included cancelled submissions.  However when counting up the number components that have been graded, this number does included cancelled submissions.  In the case where there are a lot of cancelled submissions that have already been graded (such as in the development sample course), we can compute a progress that is greater than 100%.  This fix will require a change to ```DatabaseQueries->getGradedComponentsCountByGradingSections()``` so that it no longer counts marks for canceled submissions.

**Expected behavior**
The TA progress bar should always report the correct progress.

**Comment by bmcutler** [comment] 2021-06-18 15:25
Cannot reproduce, apparently resolved by another PR

**Closed by bmcutler** 2021-06-18 15:25 UTC
Labels: Database / SQL Toolbox, TA Grading, bug, good first issue
