### ISSUE TITLE
Forum doesn't scroll to bottom of page when using filter with lots of wide categories.

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6014] opened 2020-11-11 18:50 UTC
If you enable filtering in a course with lots of wide category names, so they wrap onto a second or more lines of categories, and you view a lengthy thread, you cannot scroll to the bottom of the posts.  It stops early.  And may not be able to access the buttons at the bottom of the page.  Might depend on zoom level and width of window.

**Comment by williamjallen** [comment] 2021-05-13 14:44
After some investigation, it seems that the issue is that the sidebar and content of the forum is being set to a fixed height of 81vh, a fixed number relative to the page height.  The parent element does not have a fixed height set which I suspect is why the original author used this CSS hack.  To fix this bug, some Javascript which changes the height based on the height of the element containing the filters could be added but this would be ugly and unreliable.  The better option here would be to almost completely rewrite the forum CSS but it would be at least a week's work so I don't know if it would be worth it for one minor bug.  If there are other bugs which could be fixed by redoing the CSS or if the UI needs to be overhauled anyway, perhaps it would be reasonable.  Any changes here require changes all the way up to the parent element for the entire page which then cascade back down and require changes to the CSS for other parts of the page.

**Comment by SatendraDiwakar** [comment] 2023-02-08 14:56
Hello there,
I have provided a fix for this issue by changing some css, please review the [PR](https://github.com/Submitty/Submitty/pull/8861) and let me know if anything needs to be changed as this is my first PR here.
Thanks in advance :)

**Closed** 2023-09-07 23:46 UTC
Labels: bug, good first issue, Discussion Forum
