### ISSUE TITLE
Change how AnalysisTools repo is connected to main Submitty

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#623] opened 2016-09-11 17:38 UTC
Don't run a git pull/checkout command from the install script.  This script is run by root and is possibly not the same as the user who did the original checkout of the repo.   

Probably needs discussion of what is a better design.

**Comment by MasterOdin** [comment] 2016-09-12 03:43
What we should do is only pull and install once in install_system.sh specifying a specific commit to use. From there, we just install things like normal (rsync files from GIT_CHECKOUT_AnalysisTools to /usr/local/submitty/AnalysisTools, doing make, etc.)

**Comment by MasterOdin** [comment] 2017-06-20 19:48
This is a duplicate of #965

**Closed by MasterOdin** 2017-06-20 19:48 UTC
