### ISSUE TITLE
Display Polls Answer

### ISSUE THREAD

**Issue by hansongu123** [Submitty/Submitty#8907] opened 2023-02-16 04:44 UTC
**What problem are you trying to solve with Submitty:**
A new feature requested. An instructor now has the ability choose whether, or when to display answers of polls to students. 
![image](https://user-images.githubusercontent.com/123511202/219270061-5b70a657-f9ed-4b0f-a6ba-de5d05fc34b0.png)
![image](https://user-images.githubusercontent.com/123511202/219271340-55ba4f49-e6c9-4f7c-a052-5158372711c4.png)

**Describe the way you'd like to solve this problem:**
Examine the changes made by recent migrations. Use pull request [#7595](https://github.com/Submitty/Submitty/pull/7595) as template, create a drop-down window to give the instructor options on how to disclose polls' answers.

**Describe any potential alternatives you'd tried to solve the problem:**
Additionally, different coloring for the histogram can be applied to highlight the answers for the polls.
![image](https://user-images.githubusercontent.com/123511202/219269947-e7a85f8d-a3c6-4e94-b1c8-fc745ab40fe6.png)

**Additional context:**
This feature was first raised by issue [#7352](https://github.com/Submitty/Submitty/issues/7352) and solved by pull request [#7595](https://github.com/Submitty/Submitty/pull/7595), but later nullified by pull request [#6708](https://github.com/Submitty/Submitty/pull/6708l), the doctrine migration.
After created appropriate PR for the issue, also close both [#7352](https://github.com/Submitty/Submitty/issues/7352) and PR [#7595](https://github.com/Submitty/Submitty/pull/7595).

**Comment by bmcutler** [comment] 2023-02-16 15:33
@hansongu123 

This is not a new issue.  It is a duplicate of other issues & PRs.
If you had information to add, it should have been posted as part of the the original issue #7352, or a comment on one of the PRs.

**Closed by bmcutler** 2023-02-16 15:33 UTC
Labels: enhancement / feature request, Lecture Poll / Submini
