### ISSUE TITLE
Text not showing up in browser until clicked

### ISSUE THREAD

**Issue by ION606** [Submitty/Submitty#10620] opened 2024-06-25 01:33 UTC
**Describe the bug**

When grading a submission, the text inputs don't show any text until you click them

**Expected behavior**

The text to be shown

**To Reproduce**
1. open a gradable with a text input
2. switch to notebook view
3. see no text
4. click inside the text input
5. text appears

**Configuration**
 - OS: Linux, Windows
 - Browser Librewolf, Google Chrome

**Screenshots**

## Before click:
![image](https://github.com/Submitty/Submitty/assets/58801387/215f991a-dead-4f13-af91-ffadef23ef07)

![image](https://github.com/Submitty/Submitty/assets/58801387/c009f61f-3ebf-4029-9687-02ed9ac0bd89)

## After Click
![image](https://github.com/Submitty/Submitty/assets/58801387/1190ab20-10fb-4727-9ef8-43e08bcda82f)

![image](https://github.com/Submitty/Submitty/assets/58801387/85bd7ae2-2c52-4307-bdee-e220c0f5b552)

**Additional context**

**Comment by williamjallen** [comment] 2024-06-25 11:29
This appears to be a  duplicate of https://github.com/Submitty/Submitty/issues/10607.

**Closed by williamjallen** 2024-06-25 11:29 UTC
Labels: bug, Awaiting Triage
