### ISSUE TITLE
Unable to download submission zip of team submission

### ISSUE THREAD

**Issue by PythonCoderAS** [Submitty/Submitty#10067] opened 2023-12-13 13:44 UTC
**Describe the bug**

For an assignment I was part of a team that submitted a zip file (I was not the submitter). However, I am not able to download the submission zip file. Digging around in the JS, it attempts to open this URL: `https://submitty.cs.rpi.edu/courses/f23/csci2500/gradeable/project/download_zip?dir=submissions&user_id=sarkaa3&version=1&origin=submission&is_anon=false`

**Expected behavior**
The "download all files" button to work

**To Reproduce**
1. Be part of a team
2. Have a different member submit multiple files (or a zip file containing multiple files)
3. Attempt to download all files

**Configuration**
 - OS: [e.g. Windows, Linux, ...] MacOS
 - Browser [e.g. Chrome, Safari] Chrome

**Screenshots**

![Screenshot 2023-12-13 at 8 43 54 AM](https://github.com/Submitty/Submitty/assets/13932583/136ca30e-9fc3-4acd-b38b-d0fb175fcd17)

**Additional context**

**Comment by cjreed121** [comment] 2023-12-15 02:40
Thanks for the bug report. However, this seems to be a duplicate of #10001 so I am closing this.

**Closed by cjreed121** 2023-12-15 02:40 UTC
Labels: bug, Awaiting Triage
