### ISSUE TITLE
Grading statistics is not shown correctly in the instructor interface

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6835] opened 2021-07-28 04:01 UTC
**Describe the bug**
Grading statistics is not computed correctly when viewed through the instructor interface. Specifically, all TA grading is shown as 0/86 even though all grading has been done and the totals column shows the correct values. The "Overall Histogram" is not properly displaying the grades. Specifically, the maximum value is smaller than the actual highest overall grade.

**Expected behavior**
Grading statistics should be displayed correctly. 

**To Reproduce**
1. Navigate to the "Grading Index" of the gradeable page in the instructor's interface. In my specific example, this is gradeble exam01 in CSCI2600. The corresponding URL is: https://submitty.cs.rpi.edu/courses/u21/csci2600/gradeable/exam01/grading/details?view=all
2. Observe all TA grades shown as 0/86. At the same time, all totals are computed correctly which means that TA grades cannot all be zeros. See screenshot 1.
3. Navigate to the "Overall Histogram" tab of the gradeable page in the instructor's interface. In my specific example, this is gradeble exam01 in CSCI2600. The corresponding URL is:https://submitty.cs.rpi.edu/courses/u21/csci2600/gradeable/exam01/grading/status?nav_tab=3
4. Observe that the rightmost bucket only goes up to 84, and the maximum value reported is also shown as 84. See screenshot 2. At the same time, as screenshot 3 shows, there is at least one student who scored 97 out of 100 overall. Please note that since the tab says "Overall Histogram", I expect it to show the histogram of total scores (in my case, they are out of 100 and have a maximum value of 97), not TA scores for which Submitty currently doesn't offer a histogram, just the component averages.

**Configuration**
 - OS: Windows 10 Enterprise x64 20H2, 10.0.19042, Build 19042.1110, Windows Feature Experience Pack 120.2212.3530.0
 - Browser: Mozilla Firefox 90.0.2 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/127260987-394abdb9-8d93-4be5-8eb5-fa86edeef17c.png)
![image](https://user-images.githubusercontent.com/7108039/127261270-620a3e9d-75f7-4663-a653-98c17b3eef52.png)
![image](https://user-images.githubusercontent.com/7108039/127261274-cc5dd5da-a1ff-46cb-9432-f467364b10f9.png)

**Additional context**
I'm pretty sure this functionality worked correctly before. So, it probably got broken reasonably not that long time ago.

**Comment by loadedskiffer** [comment] 2021-07-28 19:31
@KCony I have a fix for the incorrect TA grading buttons but I can't reproduce the error with the histogram. Was the student who got the 97 enrolled in a registration section, because there have been some errors with grades received by students in this section
<img width="806" alt="histogram_issue" src="https://user-images.githubusercontent.com/66340271/127384378-1f4b30fd-30d7-4823-9bc1-96694ce5a738.PNG">

**Comment by KCony** [comment] 2021-07-29 22:56
Yes, there was actually more than one student with a 97, all enrolled in registration sections. Here is one from registration section 2:
![image](https://user-images.githubusercontent.com/7108039/127575596-21c1ddd4-1f0a-4e72-848e-ad35891c408f.png)
![image](https://user-images.githubusercontent.com/7108039/127575727-96c3a153-dd4a-4a89-b368-89f26a1fca91.png)

**Comment by loadedskiffer** [comment] 2021-07-30 14:25
> Yes, there was actually more than one student with a 97, all enrolled in registration sections. Here is one from registration section 2:
> ![image](https://user-images.githubusercontent.com/7108039/127575596-21c1ddd4-1f0a-4e72-848e-ad35891c408f.png)
> ![image](https://user-images.githubusercontent.com/7108039/127575727-96c3a153-dd4a-4a89-b368-89f26a1fca91.png)

I found the bug, fixed it and submitted a PR, should be fixed asap

**Comment by KCony** [comment] 2021-07-30 17:17
> 
> 
> > Yes, there was actually more than one student with a 97, all enrolled in registration sections. Here is one from registration section 2:
> > ![image](https://user-images.githubusercontent.com/7108039/127575596-21c1ddd4-1f0a-4e72-848e-ad35891c408f.png)
> > ![image](https://user-images.githubusercontent.com/7108039/127575727-96c3a153-dd4a-4a89-b368-89f26a1fca91.png)
> 
> I found the bug, fixed it and submitted a PR, should be fixed asap

Awesome, thanks!

**Closed** 2021-08-05 04:53 UTC
Labels: bug
