### ISSUE TITLE
Late days added through "Late Days Allowed" page are not added to the total number of late days for a student

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6377] opened 2021-05-02 13:16 UTC
**Describe the bug**
The number of additional late days granted to a student through the "Late Days Allowed" dialog is not added to the initial number of late days specified in the course configuration but replaces it. This contradicts the description on the "Late Days Allowed" page.

**Expected behavior**
Since the "Late Days Allowed" page says: "Use this form to grant students additional late days (beyond the initial number specified in the course configuration).", the number of late days entered on this page should be added to the initial number of late days specified in the course configuration instead of replacing it.

**To Reproduce**
0. Check course configuration for the initial number of late days (see screenshot 1).
1. Navigate to https://submitty.cs.rpi.edu/courses/s21/csci4960/late_days
2. Select the student, datestamp, and enter the desired number of additional late days (see screenshot 2).
3. Navigate to the latest gradeable of the student, e.g., https://submitty.cs.rpi.edu/courses/s21/csci4960/gradeable/hw05/grading/grade?who_id=y3qrkXuR0f3zHhZ&sort=id&direction=ASC
4. See the number of late days entered in the "Late Days Allowed" actually reducing the total number of late days available to the student (see screenshot 3).

**Configuration**
 - OS: Windows 10 Enterprise x64, 10.0.19042, Build 19042
 - Browser: Firefox 88.0 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/116814127-34a06a80-ab25-11eb-92cc-e96d2c302a3a.png)
![image](https://user-images.githubusercontent.com/7108039/116814193-8c3ed600-ab25-11eb-8b53-8a183acc32d2.png)
![image](https://user-images.githubusercontent.com/7108039/116814304-433b5180-ab26-11eb-9dba-3c8bde64110e.png)

**Additional context**
Either the description "Use this form to grant students additional late days (beyond the initial number specified in the course configuration)." should be changed to reflect the actual behavior or the algorithm of how additional late days are computed should be changed to match the description. The latter would make a lot more sense than just overriding the total late days (including the initial late days specified in the course configuration) every time a new value is entered through the "Late Days Allowed" page.

**Comment by bmcutler** [comment] 2021-05-30 14:00
**Describe the bug**
PR #6426 was merged too quickly.  

This issue #6377 describes one instructor's confusion with the late days interface, but the problem is not simple, and the PR makes changes that will cause other confusions.

I'm going to revert the PR and re-open this issue.

**Comment by bmcutler** [comment] 2021-05-30 14:14
This interface was designed to set/overwrite the number of late days.  This can be to increase or decrease the number of late days.

The text/on page documentation is inconsistent, but the change in functionality does not work (is unclear/unintuitive) to decrease late days.

**Comment by williamjallen** [comment] 2021-07-03 18:25
Would a good resolution for this be to simply set the number in the box to the current number of late days and change the text to be more clear that the instructor is setting the number of late days, not adding them?  It would also probably help if the input field was a number input instead of a text input.

**Comment by bmcutler** [comment] 2021-07-03 18:54
Those minor changes to the UI are ok.

**Comment by KCony** [comment] 2021-08-17 19:09
If the number of late days for the entire class is changed in the Course Settings, would that override the number of late days set for a particular student? If not, it might be super confusing. If so, would that take into account the difference or just simply overwrite the number of late days for that student?

Imagine, I initially had 7 late days for everyone, and then I gave an extra late day to some student. Then I decide to give the entire class 10 late days instead of 7, so I update the setting in the Course Settings. Would now this student still have 8 late days, i.e., less than everyone on the class? If so, it doesn't look right to me. Or is the instructor supposed to manually update all students who received an extra late day before? Seems like a lot of tedious and non-obvious work. What is worse, it would be easy for the instructor to forget about having to make this manual update and actually hurt the student by actually taking late days from them as compared to the rest of the class.

**Closed** 2021-08-28 13:24 UTC
Labels: bug
