### ISSUE TITLE
Limited Access Graders cannot TA grade teams

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6087] opened 2020-12-21 18:39 UTC
Despite the assignment being configured for grading by limited access graders, and those graders assigned to registration/rotating sections, limited access graders are not displayed as having any grading work to do on team gradeables.

**Comment by parthsrivastava100** [comment] 2020-12-27 10:16
Hey @bmcutler , I'm interested in open source and doing GSoC under your organisation, and I'd like to solve this issue. Please can I proceed forward with this one?

**Comment by loadedskiffer** [comment] 2021-06-02 15:57
I was not able to reproduce this bug so I am closing the issue.
To reproduce I :
-configured a team gradeable for limited access grading
-I logged in as grader (which is a limited access account) and tried to grade the assignment

This was what the student index page looked like
<img width="814" alt="limitedgrading" src="https://user-images.githubusercontent.com/66340271/120512410-534e8700-c399-11eb-9c69-ca430cfbadf1.PNG">

I then also created a team and made a submission for the assignment and the grader was able to grade everything like normal.

**Closed by loadedskiffer** 2021-06-02 15:57 UTC
Labels: TA Grading, bug, good first issue
