### ISSUE TITLE
Cannot use text with PDF Annotations

### ISSUE THREAD

**Issue by jchulton** [Submitty/Submitty#5813] opened 2020-08-13 08:08 UTC
**Describe the bug**
When a grader tries to add text to pdf annotations, the text will be saved at x and y coordinates 0 and 0 and the following console error occurs
![image](https://user-images.githubusercontent.com/11095297/90109813-539e6880-dd1a-11ea-9ce8-a2ba80a54d63.png)

**Expected behavior**
Text should be saved at the x and y coordinates the user clicked on when adding text

**To Reproduce**
1. As a grader, select a student to grade who has submitted a pdf
2. Open pdf annotation mode for the submitted pdf 
3. Click on the text ('A') option in the PDF annotation toolbar
4. Click somewhere on the pdf and attempt to type text annotations
5. See error

**Configuration**
 - OS: [e.g. Windows, Linux, ...]

**Screenshots**

**Additional context**

**Comment by shailpatels** [comment] 2020-08-30 03:44
@jchulton @bmcutler Is this still an issue? unable to reproduce on chrome and firefox linux

**Comment by bmcutler** [comment] 2021-06-07 05:08
Closing, will re-open with more information if it is still an issue.

**Closed by bmcutler** 2021-06-07 05:08 UTC
Labels: PDF Annotator, TA Grading, bug
