### ISSUE TITLE
Confusion in code over pin/announcement vs bookmark/favorite in the Discussion Forum

### ISSUE THREAD

**Issue by shwehtom89** [Submitty/Submitty#4520] opened 2019-09-20 03:32 UTC
**Describe the bug**
As mentioned in #4500, our definition of a star icon and pin icon run counter-intuitive to other discussion forums which may confuse users coming over from a different platform. 

Internally, the definitions of 'pinned' and 'favorites' are also confusing. In the threads table, the `pinned ` columns refers to announcements which show up as a star on the user side. Meanwhile favorites are stored in the `student_favorites` table which show up as a pin.

To address our internal concern, we could possibly create a migration script that appropriately renames the columns and makes appropriate changes in the controller/view/twig files.

@MasterOdin , @andrewaikens87 , @sak6lab thoughts?

**To Reproduce**
1. vagrant ssh
2. su postgres
3. psql
4. \c submitty_s19_sample
5. \d threads
6. See error

**Comment by bmcutler** [comment] 2019-09-20 03:55
As we discussed in the meeting, someone can make a PR with a migration to rename the  database fields & function names.  This will hopefully reduce developer confusion.

But let's not swap icons now or in the near term.

**Comment by bmcutler** [comment] 2020-02-21 04:52
Ah, here's the lost issue.... related/duplicate of #5021

**Closed** 2022-06-07 22:13 UTC
Labels: refactor / coding style, Discussion Forum, question / design / discussion needed
