### ISSUE TITLE
Bulk upload gradeables do not show "Bulk Upload" for TAs and potentially limited access graders

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#9012] opened 2023-03-07 03:06 UTC
**Describe the bug**
The bulk upload gradeable is distinct from the other types and has a different button text on the navigation view. This is what the view looks like to an instructor 

![image](https://user-images.githubusercontent.com/12129065/223309361-a925ce70-1e3e-481e-932f-78c4725d8f04.png)
----
However to a TA it looks like this in the beta release section:

![image](https://user-images.githubusercontent.com/12129065/223309533-c79ca25d-04a5-43ed-8d29-37910529e7ca.png)
----
and this is what it looks like in the open section:

![image](https://user-images.githubusercontent.com/12129065/223309628-136060d1-4606-4632-a81e-a3cb9bbe60de.png)

**Expected behavior**
If a user has access to bulk upload to a gradeable, they should see the bulk upload text same as an instructor. I haven't tested this for limited access graders but if the instructor allows them to bulk upload it should show the same thing for them

**To Reproduce**
1. Create a bulk upload gradeable
2. Select "open to TAs now" so the gradeable is not in the future section anymore
3. Look at the navigation page from a TA user 

**Configuration**
Firefox, Linux

**Screenshots**
Shown above

**Additional context**
N/A

**Comment by Onyx2406** [comment] 2023-03-10 14:36
Hi, I would like to solve this. I am working on it.

**Comment by hansongu123** [comment] 2023-03-11 00:43
@shailpatels Shail, I couldn't reproduce the error as described in the issue. I tried using different browsers too. For me, the text on the bulk upload buttons appear just normal as it just says "BULK UPLOAD" whether it is in the beta testing section or the open section for a TA. The second and third of your screenshots only appear if the assignment is not a bulk upload but rather a regular assignment. 

**Here are the pictures:**
_(Instructor's view)_
![image](https://user-images.githubusercontent.com/123511202/224453849-9ae19a93-2ad1-403c-a622-b3e4816538a9.png)
_(TA's view on beta testing section)_
![image](https://user-images.githubusercontent.com/123511202/224453881-53be4b77-efff-4ba1-9420-8b05538ec047.png)
_(TA's view on open section)_
![image](https://user-images.githubusercontent.com/123511202/224453942-ae1a6cd3-c529-40f2-b637-74073c4b7d70.png)
*notice "TEST" is a bulk upload item, and "1111" is an item of another type*

Are you confusing two items sharing a same name? Can you elaborate more on the configurations (a screenshot would help) for how this is produced?

**Comment by avijain09** [comment] 2023-03-11 07:24
I also cannot reproduce the issue. For me its working same as it is for @hansongu123.

**Comment by hansongu123** [comment] 2023-04-07 12:48
I'm closing this issue since it is not being reproduced.

Reopen this if the problem would still occur.

**Closed by hansongu123** 2023-04-07 12:48 UTC
Labels: bug, good first issue, Instructor UI, Bulk Upload / Scanned PDF Submission)
