### ISSUE TITLE
Grade buttons on mobile are huge and obscure screen making navigation difficult.

### ISSUE THREAD

**Issue by BenKelly99** [Submitty/Submitty#4461] opened 2019-09-12 01:35 UTC
**Describe the bug**
On mobile, on the gradeables page the "Grade" or "Submit" button is vertically huge and takes up almost the entire screen, requiring a lot scrolling and difficulty navigating the page. This is particularly problematic later in the semester when the number of gradeables is very large.

**Expected behavior**
The button should not be so massive as to obscure the screen.

**To Reproduce**
1. Go to the gradeables page on mobile.
2. See error

**Configuration**
 - OS: IoS/Mobile
 - Browser Chrome

**Screenshots**
![Image-1](https://user-images.githubusercontent.com/11927934/64746863-3befac00-d4db-11e9-8cb2-fe9084b5565f.jpg)

**Additional context**
Would be great for mentors who grade labs on their phone!

**Comment by MasterOdin** [comment] 2019-09-12 06:54
Duplicate of #4390

**Closed by MasterOdin** 2019-09-12 06:54 UTC
Labels: bug
