### ISSUE TITLE
Submission message displaying "Submit" incorrectly.

### ISSUE THREAD

**Issue by RyanTonerCode** [Submitty/Submitty#3781] opened 2019-06-03 23:54 UTC
**Describe the bug**
https://github.com/Submitty/Submitty/blob/715922e28dae8652e11a90edb412d19c242db7ca/site/config/course_template.json#L11

Here is the output:
![image](https://user-images.githubusercontent.com/12375651/58841816-8f7b6f80-8639-11e9-8c5a-1428119f8fb6.png)

**Expected behavior**
Either link to submit behavior or fix the literal.

I think this could be happening because JSON is handling the escape character erroneously. You might try another escape with \\ or \\\ followed by the ".

**Comment by brandonmreid** [comment] 2019-06-04 03:15
Duplicate of #3513

**Closed** 2019-06-04 21:31 UTC
Labels: bug
