### ISSUE TITLE
Lecture Poll (Sub-mini) requests

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6036] opened 2020-12-01 17:49 UTC
- [x] Instructor UI: have the date for a new poll default to today.  I think it currently starts blank and my browser is suggesting a date from a month ago.  (requires lots of clicks just to get to today.)

- [x] Instructor UI: have an indication on the main page if a poll doesn't have at least one correct answer selected.  Or maybe don't let me create a poll unless I select a correct answer.  We can discuss.

- [x] Instead of centering the title of the poll on the main page, let's left justify it.

- [ ] Let's have a way for the instructor to view the student view of the poll.  (Currently, all I can do is show the interface to edit the poll, which also has the correct answer(s) selected.)

- [x] Let's discuss:  an option for the instructor to "publish" the graph of the results (probably only once the poll is closed).  This should be an option, not automatic.  Sometimes, the poll has a 'correct' answer, and I want to re-use the poll...  so I don't want it published.  Sometimes, it is an opinion poll and I would like students to be able to see each others answers.  Sometimes we might light to publish the results while it is still open and accepting results.  This should probably be another column of checkboxes. 

... hopefully these aren't all repeats from other open issues :)

**Comment by bmcutler** [comment] 2020-12-02 17:38
The "Delete" button the instructor UI is rarely used, and can take up less room...  replace it with a trash can.
The "Edit poll" button the instructor UI could be replaced with the pencil icon.
Let's standardize the styling of this page to make it more similar to the all gradeables page instructor view.

**Comment by wdturner** [comment] 2021-05-13 17:25
I am happy to take a look, but was this intended to be assigned to me?

**Comment by sbelsk** [comment] 2021-05-14 14:17
I looked into some of the problems listed in the original comment:

1. I could not reproduce the issue of the date for the new poll defaulting to a date different than today.
I assume that it functions properly since the code used to select the date is used elsewhere on Submitty (late days, gradeables, forum) where that was no such issue.

2. The indication/message for having at least one correct answer selected was resolved in PR https://github.com/Submitty/Submitty/pull/6181

3. For the third point "Instead of centering the title of the poll on the main page, let's left justify it." -- what page is meant by "main page" (the instructor's Edit Poll page, student's View Poll page, or Poll summary for both students and instructors)?

**Comment by bmcutler** [comment] 2021-05-14 20:49
The student view seems to have the titles center, while the instructor is left justified.  I think both should be left justified.  Also, there seems to be a large amount of a horizontal padding/space between the columns forcing the title to wrap earlier than necessary if it is lengthy.  [Note, I cannot currently access my courses from the last 2 terms to remind myself what a full course's worth of poll titles look like]

**Comment by bmcutler** [comment] 2021-05-15 20:35
Here's an example of ugly wrapping -- the pencil & trash can should be to the left of the wrapped title.  And the title column should be wider than the columns with just the check boxes.

<img width="846" alt="Screen Shot 2021-05-15 at 4 29 44 PM" src="https://user-images.githubusercontent.com/5871417/118377456-52e17e00-b59b-11eb-8c78-14f51b8286fd.png">

And here's a different example showing the centered student view:

<img width="691" alt="Screen Shot 2021-05-15 at 4 33 22 PM" src="https://user-images.githubusercontent.com/5871417/118377468-5ffe6d00-b59b-11eb-9d1f-45a19f144810.png">

**Comment by MasterOdin** [comment] 2021-05-19 02:20
> I could not reproduce the issue of the date for the new poll defaulting to a date different than today.
I assume that it functions properly since the code used to select the date is used elsewhere on Submitty (late days, gradeables, forum) where that was no such issue.

Double checking this, on going to http://localhost:1501/courses/s21/sample/polls/newPoll, the "Expected release date" box is empty for me on macOS / Chrome. Additionally, we should disable `autocomplete` on that box as for me, it shows a dropdown over the calendar popup that makes it impossible to interact with the calendar.

**Closed** 2022-06-07 22:06 UTC
Labels: Lecture Poll / Submini
