### ISSUE TITLE
python: f-string parser error

### ISSUE THREAD

**Issue by MKronmiler** [Submitty/Submitty#7565] opened 2022-01-24 17:57 UTC
**Describe the bug**
When submitting to the autograder, if an fstring statement exists outside of a print(), the autograder will throw the following error into student STDERR

`
1[91mParser error: UnexpectedToken (StringToken {token_span = SpanCoLinear {span_filename = "/var/local/submitty/autograding_tmp/untrusted03/tmp/TMP_WORK/test05/part3/hw1_part3.py", span_row = 24, span_start_column = 8, span_end_column = 25}, token_literal = "'{width}x{height}'"})
2[0m
`

triggered by the following line: 
`dim = f'{width}x{height}'`

width and height are integers

**Expected behavior**
fstring is interpreted

**To Reproduce**
1. instantiate an fstring outside of a print statement
2. submit code to submitty

**Configuration**
 - OS: Windows
 - Browser: Firefox

**Screenshots**

**Additional context**
Behavior observed on submitty.cs.rpi.edu

**Comment by MasterOdin** [comment] 2022-01-25 13:10
This was on trying to use `submitty_count` utility, or how were you trying to grade this assignment?

**Comment by MKronmiler** [comment] 2022-01-25 15:12
I was submitting a homework file for grading. CSCI-1100 Homework 1 Part 3

Here is the full program (not sure why the codeblock isn't working properly):

from math import ceil, floor

if True:
    f_char = input("Enter frame character ==> ").strip()
    print(f_char)

    height = int(input("Height of box ==> "))
    print(height)

    width = int(input("Width of box ==> "))
    print(width)

else:
    f_char = '.'
    height = 8
    width = 11


print("\nBox:")

**dim = f'{width}x{height}'**
dim_length = len(dim) #get the length of the string

lid = f_char*width 
box_hollow = f_char + (" " * (width-2)) + f_char + '\n'
box_dim = ((width-2)/2)-(dim_length/2) #calculating 1/2 of the white space around the dimension string
box_center = f_char + (" " * floor(((width-2)/2)-(dim_length/2))) + dim + (" " * ceil(((width-2)/2)-(dim_length/2))) + f_char

print(lid)
print(box_hollow*floor((height-3)/2),end = '')
print(box_center)
print(box_hollow*ceil((height-3)/2),end = '')
print(lid)

**Comment by williamjallen** [comment] 2022-01-25 18:08
@MKronmiler I edited your message to reduce the possibility of plagiarism of any sort since it seemed to be a large portion of a homework assignment.  If I edited the wrong portion, please feel free to revert the changes.  

Regarding the issue itself, I believe that CSCI-1100 at RPI uses the `submitty_count` utility mentioned above, which does not support the latest Python features, so that may be the source of the issue.

**Comment by MasterOdin** [comment] 2022-01-25 18:39
In that case, closing this as a duplicate of #4701.

**Closed by MasterOdin** 2022-01-25 18:39 UTC
Labels: bug
