### ISSUE TITLE
Course material is not displaying for students

### ISSUE THREAD

**Issue by josethomas98** [Submitty/Submitty#3098] opened 2018-11-06 05:48 UTC
The course material section for the instructor which contains a checkbox for "share to students" is sending the material file to the server and the server is giving status 200 but on refresh the checkbox remain unchecked and thus the students are not able to view the update made by the instructor regarding upload of course material. Is there anything else I need to do?

**Comment by bmcutler** [comment] 2018-11-06 07:41
Hi Jose,
What version of Submitty do you have installed?  We had some bugs in the feature when we first rolled it out at the start of term.  This sounds familiar.  But I believe the most recent code works fine (some of my colleagues are using the feature).
Barb

**Comment by bmcutler** [comment] 2019-01-17 06:07
Hi Jose,

I just realized that the problem is from incorrect permissions on a directory.

It was fixed in PR #3213 

Barb

**Closed by bmcutler** 2019-01-17 06:07 UTC
