### ISSUE TITLE
Minor issues in new gradeable

### ISSUE THREAD

**Issue by jchulton** [Submitty/Submitty#2076] opened 2018-06-01 21:06 UTC
1. The error: GET http://trentrichardson.com/examples/timepicker/jquery-ui-timepicker-addon.css 403 (Forbidden) appears on the console (doesn't seem to effect much.
2. After creation a course, all of the buttons on the main page say "Need to build samples.sh"
3.  After the warning DATE CONSISTENCY:  [Warning] Manual Grading Open Date should be >= Due Date (+ max allowed late days) the gradeable just creates anyway.

Just a couple of things I noticed, none are pressing though.

**Comment by bmcutler** [comment] 2018-06-04 01:37
2. is not a bug
3. is also ok...  but this is a common confusion, date panel redesign and text/warning/error messages should be made concise & clear.

**Comment by KevinMackenzie** [comment] 2018-06-12 14:36
This got fixed when #2068 was merged

**Closed by KevinMackenzie** 2018-06-12 14:36 UTC
Labels: bug, low priority
