### ISSUE TITLE
Incorrect sections in auto-created customization.json

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8471] opened 2022-10-03 02:20 UTC
**Describe the bug**

Here are the registration sections for my course:  
A "STAFF" section + sections 1-10.  Note:  The staff section was created first.

<img width="311" alt="Screen Shot 2022-10-02 at 10 15 59 PM" src="https://user-images.githubusercontent.com/5871417/193490033-107c8cc9-2414-4b0c-8ee7-b8adbf3d94fe.png">

Then I used the form to create the customization.json for Rainbow Grades:
Grade Reports -> Web-Based Rainbow Grades Customization

The "Section Labels" portion of the UI is incorrect.  There is no section 11.  And we are missing Section 1.

<img width="215" alt="Screen Shot 2022-10-02 at 10 17 40 PM" src="https://user-images.githubusercontent.com/5871417/193490186-f6f49ce3-ee0b-4070-a8c9-4bce18cdf658.png">

This error propagates to the auto-generated customization.json:

<img width="185" alt="Screen Shot 2022-10-02 at 10 19 01 PM" src="https://user-images.githubusercontent.com/5871417/193490300-c90acc8b-8bff-468d-af82-c149b26589b4.png">

**Comment by solomonsanderson** [comment] 2022-11-16 15:15
I'd like to try and fix this. Could anyone give me some pointers on where to start?

**Comment by photon0205** [comment] 2023-01-11 23:01
I would like to work upon this, can you assign this to me?

**Comment by Aadijindal07** [comment] 2023-01-31 15:21
I would love and be absolutely honored to contribute so kindly assign me these are the steps i will follow

Verify the source of the data: Make sure that the data used to generate the customization.json file is up-to-date and accurate.

Modify the form: Update the form used to generate the customization.json file to match the registration sections. Ensure that section 1 and the staff section are included, and that there is no section 11.

Regenerate the customization.json: Use the updated form to regenerate the customization.json file.

Test the changes: Test the changes to ensure that the issue is resolved and that the section labels are correctly displayed in the UI.

Document the changes: Document the changes made to the form and the customization.json file for future reference.

**Comment by swapnanildas** [comment] 2023-02-05 00:08
i'd like to try and fix this issue, can someone please assign me this issue?

**Closed** 2023-02-13 23:13 UTC
Labels: bug, Rainbow Grades, good first issue, Instructor UI
