### ISSUE TITLE
Gradeable build / autograding stuck at queue

### ISSUE THREAD

**Issue by nlentzas** [Submitty/Submitty#4590] opened 2019-10-03 14:52 UTC
When adding a new gradeable the build phase starts indicating that it is in the rebuild queue. 
If i run the Build_<course>.sh using SSH the gradeable is built fine. But then autograding is also stuck at the same grading queue. Any idea what the cause might be?

**Comment by bmcutler** [comment] 2019-10-03 19:28
I think this is a duplicate of #4397

**Closed by bmcutler** 2019-10-03 19:29 UTC
Labels: bug

**Comment by nlentzas** [comment] 2019-10-04 10:03
The difference with the already reported bug is that the build doesn't fail, it is stuck at queue and there isn't a second build job at the queue.
