### ISSUE TITLE
Looking to overall comments from another marker shows the main submitty page under the tab

### ISSUE THREAD

**Issue by dpshelio** [Submitty/Submitty#7479] opened 2021-12-22 14:43 UTC
**Describe the bug**
When marking, on the rubric panel, and Overall Comment. If I click on another marker comments, the tab loads the main page, instead of showing the comments as expected.

**Expected behavior**
Show the comments left from another marker

**To Reproduce**
1.  Visit a submission already graded by another marker where overall comments had been left
2.  Open the rubric panel and scroll to the bottom to the "overall comments" section
3.  Click on the tab with the name of the other marker
4.  It loads the main page, instead of showing the comments left by the other marker.

**Configuration**
 - OS: Linux
 - Browser Firefox 95.0.1 (64-bit)

**Screenshots**
![submitty_comments](https://user-images.githubusercontent.com/963242/147108815-3a6f004d-5c51-463b-ac6e-73a196713733.gif)

**Additional context**
I've not had the time to find when this has been introduced, or test a newer version on the production machine. The version I'm using is 663841de5c0e4134adc94eb63eaed0fef93a5678 (from mid Nov). #7296 may have a fix for it, as it's the only new change after the version I'm using.

**Comment by williamjallen** [comment] 2021-12-22 16:06
I am unable to reproduce this on master.  I believe #7367 addressed the issue you are experiencing so I will close this issue.  If you are still experiencing this issue after upgrading to the latest version of Submitty, please feel free to re-open the issue.

**Closed by williamjallen** 2021-12-22 16:06 UTC
Labels: bug
