### ISSUE TITLE
Submitty does not appear full width on Firefox Firefox 68, 64 bit Ubuntu 18.04

### ISSUE THREAD

**Issue by Fenn-CS** [Submitty/Submitty#4155] opened 2019-07-20 05:19 UTC
**Describe the bug**
Submitty does not appear full width on Firefox `Firefox 68, 64 bit Ubuntu 18.04`
![Screenshot_2019-07-20 Submitty Sample Gradeables](https://user-images.githubusercontent.com/14317775/61574312-d4f2df80-aab5-11e9-8855-f7702b813c1a.png)
![Screenshot_2019-07-20 Submitty](https://user-images.githubusercontent.com/14317775/61574313-d58b7600-aab5-11e9-8b76-a5eb9f0e1e94.png)

**Expected behavior**
Should appear full width like on chrome
![Screenshot from 2019-07-20 06-16-23](https://user-images.githubusercontent.com/14317775/61574322-f94ebc00-aab5-11e9-85d3-abd854e4edaa.png)

**To Reproduce**
1. Open submission ui on Firefox 68, ubuntu and possibly others.

**Comment by mktung** [comment] 2019-07-22 13:37
I cannot replicate this using Firefox 68 on Ubuntu - even after disabling flex. Out of curiosity, does setting `<html>` or `<body>` to have `min-width: 100vw` fix it? Also, does `#submitty-body` have `width: 100%` ?

**Comment by Kevin-MM** [comment] 2019-07-22 18:55
Unable to replicate on Firefox 68

**Comment by Fenn-CS** [comment] 2019-07-23 15:05
@mktung 
`<body>` actually occupies all screen as you can see here.
![Screenshot from 2019-07-23 16-01-03](https://user-images.githubusercontent.com/14317775/61723121-73579d00-ad63-11e9-8f13-76b5bd593d67.png)

As for `#submitty-body`, yes we have `width:100%` but the rule does not seem to be effective! because changing it has no effect. Setting it even to zero does not affect anything.

What a weird thing! I don't see it on chrome.

**Comment by mktung** [comment] 2019-07-23 15:32
Try replacing `width: 100%` with `display: flex` on `#submitty-body`

If that doesn't work I have no clue what it could be

**Comment by bmcutler** [comment] 2020-02-22 03:53
Closing this because we are unable to reproduce. 
Please reopen if there are more specific instructions to reproduce on the current master branch.

**Closed by bmcutler** 2020-02-22 03:53 UTC
Labels: good first issue
